version: "3.8"

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80" # API Requests
      - "8080:8080" # Dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - public-net

  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - data-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASS:-secret}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - data-net
    ports:
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 20s

  chat-gateway:
    build:
      context: ../chat-gateway
      dockerfile: Dockerfile
    container_name: chat-gateway
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
    labels:
      - "traefik.enable=true"
      # Requests with /ws (WebSockets) or /api/ticket beginnen, are routed here:
      - "traefik.http.routers.chat-gateway.rule=PathPrefix(`/ws`, `/api/ticket`)"
      # .NET 8 Web APIs 8080
      - "traefik.http.services.chat-gateway.loadbalancer.server.port=8080"
    networks:
      - public-net # Talk to Traefik
      - data-net # Talsk to Redis and RabbitMQ
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  user-service:
    build:
      context: ../user-service
      dockerfile: Dockerfile
    container_name: user-service
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    labels:
      - "traefik.enable=true"
      # All Requests from /api/users are routed to this Service
      - "traefik.http.routers.user-service.rule=PathPrefix(`/api/users`)"
      - "traefik.http.services.user-service.loadbalancer.server.port=8080"
    networks:
      - public-net

  # No Traefik Routing, only internal communication with RabbitMQ. These are background workers that process messages from RabbitMQ.
  storage-worker:
    build:
      context: ../storage-service
      dockerfile: Dockerfile
    container_name: storage-worker
    restart: unless-stopped
    environment:
      - DOTNET_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
    networks:
      - data-net # Talks to RabbitMQ
    depends_on:
      rabbitmq:
        condition: service_healthy

  delivery-worker:
    build:
      context: ../delivery-service
      dockerfile: Dockerfile
    container_name: delivery-worker
    restart: unless-stopped
    environment:
      - DOTNET_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
    networks:
      - data-net # Talks to RabbitMQ
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  public-net:
    driver: bridge
  internal-net:
    driver: bridge
    internal: true
  data-net:
    driver: bridge
    internal: true

volumes:
  redis_data:
  rabbitmq_data:
