version: '3.8'

services:
  database:
    image: postgres:18.4
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - data-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - data-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - data-net
      - public-net
    ports:
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 20s

  # chat-gateway: get from doku

  # auth-service: get from doku

  # user-directory: get from doku

  # storage-worker: get from doku

   # delivery-worker: get from doku

networks:
  public-net:
    driver: bridge
  internal-net:
    driver: bridge
    internal: true
  data-net:
    driver: bridge
    internal: true

volumes:
  db_data:
  redis_data:
  rabbitmq_data: